name: NX_CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: spliting string
      uses: winterjung/split@v2.1.0
      id: repo
      with:
        msg: ${{ github.repository }}
        separator: '/'
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        submodules: recursive
    - name: Build
      run: |
        git config --global --add safe.directory `pwd`;
        git submodule update --init --recursive
        sed -i "s#swkbdConfigSetStringLenMaxExt#swkbdConfigSetStringLenMin#g" libs/borealis/library/lib/swkbd.cpp
        make
    - name: Upload file
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.repo.outputs._1 }} 
        path: ./*.nro
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.repo_token }}
        file: ./*.nro
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
